apiVersion: apps/v1
kind: Deployment
metadata:
        name: redis-deployment
spec:
        replicas : 30
        selector:
                matchLabels:
                        component: web
        template:
                metadata:
                        labels:
                                component: web
                spec:
                        containers:
                                - name: client
                                  image: redis
                                  ports:
                                          - containerPort: 6379
