apiVersion: v1
kind: Pod
metadata:
        name: redis-pod
        labels:
                component: web
spec:
        containers:
                - name: client
                  image: redis
                  ports:
                        - containerPort: 6379

